default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password: rootpasswordgiven
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: story_db

test:
  <<: *default
  database: test_story_db

production:
  <<: *default
  database: production_story_db