static_pages:
  help:
    link1: "https://www.google.com.vn/"
Member:
  name:
    maximum: 50
  email:
    maximum: 255
  password:
    minimum: 6
  size:
    index: 50
    avatar: 80
links:
  avatar_email: "http://gravatar.com/emails"
paginate:
  per_page: 5
Author:
  name:
    maximum: 40
Story:
  name:
    maximum: 40
  describe:
    minimum: 20
Comment:
  content: 140
upload:
  width: 456
  height: 300
  thumb: 250
  thumb2: 200
Chapter:
  content:
    minimum: 20
  name:
    maximum: 20
limit: 5
